### ISSUE TITLE
importer failed one record

### ISSUE THREAD

**Issue by PowIlove** [HydrologicEngineeringCenter/Vortex#29] opened 2021-05-04 01:20 UTC
hi, i am having problems with this script, when i imported the grb files format to dss file i have been problems with result o the records because if i got 24 dates of precipitation daily just i get 1 record in my document dss and not get 24 files of precipitation
![image](https://user-images.githubusercontent.com/59849903/116951099-e16d0b80-ac3b-11eb-85dc-ea8436c1f50d.png)

i have other question, its possible that vortex tool work with a specific operating system?

**Comment by tombrauer** [comment] 2021-05-04 03:38
Greetings @PowIlove, Can you upload a zip file with your *.grb files?

We've done some work to make multi-platform Vortex distributions but I've only been posting builds for Windows x64. Which platform are you looking for?

**Comment by PowIlove** [comment] 2021-05-04 04:13
hello @tombrauer yes of course immediately i upload the zip; referent to platform i am using vortex v0.10.20. i remember that had to use JDK cause the begining i can't to open the script of import (appeared errors) but later that put the JDK and i can to open and run the script but later appear it with this mistake of only one record in dss file.
[NLDAS_GRB_ONEDAY_DATA.zip](https://github.com/HydrologicEngineeringCenter/Vortex/files/6418947/NLDAS_GRB_ONEDAY_DATA.zip)

**Comment by PowIlove** [comment] 2021-05-04 04:15
`C:\vortex-0.10.20\bin>SET "PATH=.\gdal;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\jesus\AppData\Local\Microsoft\WindowsApps;"

C:\vortex-0.10.20\bin>SET "GDAL_DATA=.\gdal\gdal-data"

C:\vortex-0.10.20\bin>SET "PROJ_LIB=.\gdal\projlib"

C:\vortex-0.10.20\bin>"..\jre\bin\java.exe" --module-path "..\jmods" --add-modules javafx.controls,javafx.fxml -Djavafx.cachedir=. -Djava.library.path=".;.\gdal" -cp ..\lib\importer.jar;..\lib\* importer.MetDataImportWizard

OS Name is Windows 10


    -----DSS---ZOPEN:  Existing File Opened,  File: C:\Users\jesus\Documents\test\test14.dss
                       Unit:    3;  DSS Versions - Software: 6-YN, File: 6-QF,  Library 7-HK
 -----DSS---ZWRITE Unit    3; Vers.    1:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.    2:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.    3:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.    4:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.    5:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.    6:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.    7:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.    8:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.    9:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.   10:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.   11:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.   12:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.   13:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.   14:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.   15:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.   16:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.   17:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.   18:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.   19:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.   20:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.   21:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.   22:  ///PRECIPITATION////
 -----DSS---ZWRITE Unit    3; Vers.   23:  ///PRECIPITATION////
    -----DSS---zclose6 Unit:    3,   File: C:\Users\jesus\Documents\test\test14.dss
               Pointer Utilization:  0.25
               Number of Records:      1
               File Size:     76.7  Kbytes
               Percent Inactive: 163.8
               Number of Reads:      118`

**Comment by tombrauer** [comment] 2021-05-04 13:49
@PowIlove I tested your dataset. I see the grids coming in with dates.
https://user-images.githubusercontent.com/9610094/117013372-a8b54c80-aca4-11eb-8e21-030091d29d65.mp4

**Comment by PowIlove** [comment] 2021-05-04 14:57
i did the same that you but i continue having the same result i don't know why, just for know maybe i need have other components in my windows x64? or a special version of hec-dss?

**Comment by tombrauer** [comment] 2021-05-04 16:18
I've tried a few different things and I'm unable to reproduce. Maybe you can create a video so that I can see each step that you take.

**Comment by PowIlove** [comment] 2021-05-04 22:17
yeah of course i already put the video right now

https://user-images.githubusercontent.com/59849903/117076694-aaeec980-aceb-11eb-8260-a24a95957717.mp4

**Comment by PowIlove** [comment] 2021-05-05 07:34
I'm sorry for some reason the video got up incomplete, i upload the video again

https://user-images.githubusercontent.com/59849903/117109513-a4873e80-ad39-11eb-95c9-3bcf920c8848.mp4

**Comment by PowIlove** [comment] 2021-05-07 01:20
Hi @tombrauer excuse me again, but will be possible have like a little bit tutorial about as use of this tools, actuallity i'm working with the grid process for a project of my university in master degress level, so i would like as learn to use it, i hope that be possible, thanks for all

**Comment by danhamill** [comment] 2021-05-07 01:45
Is dss, could you have the pathnames condensed?

https://www.hec.usace.army.mil/confluence/rtsdocs/rtsum/3.2.1/using-hec-
dssvue/dss-pathnames

On May 6, 2021, nnk2193 ***@***.***> wrote:
> Hi @tombrauer <https://github.com/tombrauer> excuse me again, but will
> be possible have like a little bit tutorial about as use of this
> tools, actuallity i'm working with the grid process for a project of
> my university in master degress level, so i would like as learn to use
> it, i hope that be possible, thanks for all
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/HydrologicEngineeringCenter/Vortex/issues/29#issuecomment-
833989292>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ACX5GUTKICJKHVKJN5Y7MX3TMM555ANCNFSM44BZMEMA>.

**Comment by tombrauer** [comment] 2021-05-25 23:10
@PowIlove what is the Locale setting of your system?
![image](https://user-images.githubusercontent.com/9610094/119579613-a6aa4f00-bd73-11eb-9d0b-aeb3ef456a68.png)

**Comment by JesusT1995** [comment] 2021-05-25 23:37
Hi @tombrauer is this 
![image](https://user-images.githubusercontent.com/84552006/119581458-706ece80-bd77-11eb-98cd-2480d3a5927e.png)

**Comment by PowIlove** [comment] 2021-05-25 23:38
is this 
![image](https://user-images.githubusercontent.com/59849903/119581520-94321480-bd77-11eb-9e36-f946548293f6.png)

**Comment by PowIlove** [comment] 2021-05-26 00:35
@tombrauer thanks so much finally i can to use the tool, if it was that part

**Comment by PowIlove** [comment] 2021-06-15 17:58
Hi dear @tombrauer i was working in vortex again and i was wondering if this tool supports other formats such as .asc i wanted to do some tests with it but I got this error
![image](https://user-images.githubusercontent.com/59849903/122100878-85fc7480-cdc8-11eb-8891-6e5c300ac58e.png)

I don't know if there is a solution for this error

**Comment by tombrauer** [comment] 2021-06-15 18:32
@PowIlove This issue seems unrelated to the one that was initially reported. Can you close this issue and create a new one?

**Closed** 2021-06-15 18:34 UTC
